### ISSUE TITLE
go get with this repo is broken on pre-go-1.10 machines

### ISSUE THREAD

**Issue by iamtheddrman** [posener/wstest#28]
Due to Golang's insane lack of semantic versioning, this repo is now broken for our codebase, which uses go 1.8. The Gophers suggest baking the version number of the tool into the repo name, and creating new repos for each major version of the tool.

Would it be possible to create a wstest-v2 or wstest-go-1-10 repo for the new go 1.10-related changes, and leave this repo with the original API? To work around this, I had to fork the repo and roll back the last 6 commits to get it back to a compatible state.

I understand that this is a lot of work, but this repo simply no longer works for anything other than go 1.10 without using a third-party package manager.

**Comment by posener** [comment]
Hey, I am glad to hear that you are using this repo, and sorry to hear that your codebase broke because of it.
Are you using any sort of vendoring? you could set the version of this repo to v0.1 with a vendor management system.

**Comment by iamtheddrman** [comment]
Unfortunately, we are not. I tried it out when vendoring was first previewed, and it was a total mess. I'm sure it's improved by now, but I work at a startup and it's getting hard to ask for more time to try the same old things out again and again... We're pretty much as vanilla Golang as possible. No third party PMs, no vendoring utilities, etc.

**Comment by posener** [comment]
Well, you have several options here, those are all already solved problems.
* Use vendoring, it will freeze your dependencies, make your code more stable, and enable usage of a library of a specific package (take a look at [dep](https://github.com/golang/dep)).
* Upgrade go to 1.10, it should be an easy upgrade, it is recommended by the go team, and there is no actual reason no to do so.
There is no reason to create a fork with different name because of this change.

**Comment by posener** [comment]
I think this is no longer relevant.
